spring:
  application:
    name: et-naming-server
  config:
    activate:
      on-profile: prod
server:
  port: 8080
eureka:
  instance:
    hostname: naming-server    # If want hostname as localhost then uncomment it, i am using ip address so commented it
    # prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    self-register: false

